### PR TITLE
Add alias interfaces and index interfaces

### PR DESCRIPTION
**Pull request by yhmo**
Signed-off-by: yhmo <yihua.mo@zilliz.com>

#16

### CODE REVIEW

**Comment by ArkaprabhaChakraborty** [comment]
@yhmo there are lint errors

**Comment by ArkaprabhaChakraborty** [comment]
Yep this is where the problem begins :) conflicts :)

**Comment by yhmo** [comment]
@ArkaprabhaChakraborty @matrixji 
The conflict has been fixed. Need lgtm label again.

**Pull request merged**
