### PR TITLE
Build test for rpm package

### PR DESCRIPTION
**Pull request by matrixji**
Signed-off-by: Ji Bin <matrixji@live.com>

### CODE REVIEW

**Comment by yhmo** [comment]
I tried `make install`, the headers are installed into `/usr/local/include`:
-- Installing: /usr/local/include/BaseParam.h
-- Installing: /usr/local/include/ConnectParam.h
-- Installing: /usr/local/include/DataType.h
-- Installing: /usr/local/include/CollectionStat.h
-- Installing: /usr/local/include/PartitionStat.h
-- Installing: /usr/local/include/IndexState.h
-- Installing: /usr/local/include/PartitionInfo.h
-- Installing: /usr/local/include/IDArray.h
-- Installing: /usr/local/include/QueryArguments.h
-- Installing: /usr/local/include/QueryResults.h
-- Installing: /usr/local/include/CollectionInfo.h
-- Installing: /usr/local/include/IndexDesc.h
-- Installing: /usr/local/include/SegmentInfo.h
-- Installing: /usr/local/include/CompactionPlan.h
-- Installing: /usr/local/include/CompactionState.h
-- Installing: /usr/local/include/Constants.h
-- Installing: /usr/local/include/FieldSchema.h
-- Installing: /usr/local/include/ProgressMonitor.h
-- Installing: /usr/local/include/CollectionSchema.h
-- Installing: /usr/local/include/MetricType.h
-- Installing: /usr/local/include/SearchResults.h
-- Installing: /usr/local/include/CollectionDesc.h
-- Installing: /usr/local/include/FieldData.h
-- Installing: /usr/local/include/SearchArguments.h
-- Installing: /usr/local/include/Status.h
-- Installing: /usr/local/include/MilvusClient.h

Can we put them into a folder? The folder name can be `libmilvus-2.0`.

**Comment by matrixji** [comment]
> I tried `make install`, the headers are installed into `/usr/local/include`: -- Installing: /usr/local/include/BaseParam.h -- Installing: /usr/local/include/ConnectParam.h -- Installing: /usr/local/include/DataType.h -- Installing: /usr/local/include/CollectionStat.h -- Installing: /usr/local/include/PartitionStat.h -- Installing: /usr/local/include/IndexState.h -- Installing: /usr/local/include/PartitionInfo.h -- Installing: /usr/local/include/IDArray.h -- Installing: /usr/local/include/QueryArguments.h -- Installing: /usr/local/include/QueryResults.h -- Installing: /usr/local/include/CollectionInfo.h -- Installing: /usr/local/include/IndexDesc.h -- Installing: /usr/local/include/SegmentInfo.h -- Installing: /usr/local/include/CompactionPlan.h -- Installing: /usr/local/include/CompactionState.h -- Installing: /usr/local/include/Constants.h -- Installing: /usr/local/include/FieldSchema.h -- Installing: /usr/local/include/ProgressMonitor.h -- Installing: /usr/local/include/CollectionSchema.h -- Installing: /usr/local/include/MetricType.h -- Installing: /usr/local/include/SearchResults.h -- Installing: /usr/local/include/CollectionDesc.h -- Installing: /usr/local/include/FieldData.h -- Installing: /usr/local/include/SearchArguments.h -- Installing: /usr/local/include/Status.h -- Installing: /usr/local/include/MilvusClient.h
> 
> Can we put them into a folder? The folder name can be `libmilvus-sdk-2.0`. For example: -- Installing: /usr/local/include/libmilvus-sdk-2.0/SearchResults.h

Yes, this PR also fixes this issue. Installing headers in a subfolder named `milvus`, like:
```
-- Installing: /usr/local/include/milvus
-- Installing: /usr/local/include/milvus/MilvusClient.h
-- Installing: /usr/local/include/milvus/Status.h
-- Installing: /usr/local/include/milvus/param
-- Installing: /usr/local/include/milvus/param/BaseParam.h
-- Installing: /usr/local/include/milvus/types
-- Installing: /usr/local/include/milvus/types/CalcDistanceArguments.h
-- Installing: /usr/local/include/milvus/types/CollectionDesc.h
-- Installing: /usr/local/include/milvus/types/CollectionInfo.h
-- Installing: /usr/local/include/milvus/types/CollectionSchema.h
-- Installing: /usr/local/include/milvus/types/CollectionStat.h
-- Installing: /usr/local/include/milvus/types/CompactionPlan.h
-- Installing: /usr/local/include/milvus/types/CompactionState.h
-- Installing: /usr/local/include/milvus/types/ConnectParam.h
-- Installing: /usr/local/include/milvus/types/Constants.h
-- Installing: /usr/local/include/milvus/types/DataType.h
-- Installing: /usr/local/include/milvus/types/DistanceArray.h
-- Installing: /usr/local/include/milvus/types/FieldData.h
-- Installing: /usr/local/include/milvus/types/FieldSchema.h
-- Installing: /usr/local/include/milvus/types/IDArray.h
-- Installing: /usr/local/include/milvus/types/IndexDesc.h
-- Installing: /usr/local/include/milvus/types/IndexState.h
-- Installing: /usr/local/include/milvus/types/MetricType.h
-- Installing: /usr/local/include/milvus/types/PartitionInfo.h
-- Installing: /usr/local/include/milvus/types/PartitionStat.h
-- Installing: /usr/local/include/milvus/types/ProgressMonitor.h
-- Installing: /usr/local/include/milvus/types/QueryArguments.h
-- Installing: /usr/local/include/milvus/types/QueryResults.h
-- Installing: /usr/local/include/milvus/types/SearchArguments.h
-- Installing: /usr/local/include/milvus/types/SearchResults.h
-- Installing: /usr/local/include/milvus/types/SegmentInfo.h
```

**Pull request merged**
