### PR TITLE
Add GetCollectionStatistics() interface

### LINKED ISSUE #32: Implement GetCollectionStatistics() interface
This api depends on Flush()

### PR DESCRIPTION
**Pull request by ArkaprabhaChakraborty**
fixes #32 
Signed-off-by: ArkaprabhaChakraborty <chakrabortyarkaprabha998@gmail.com>

### CODE REVIEW

**Comment by matrixji** [comment]
Looks good to me, except it needs to squash commits to one.

**Comment by ArkaprabhaChakraborty** [comment]
> Looks good to me, except it needs to squash commits to one.

I'm adding a flush test too. After that I will squash all commits

**Comment by ArkaprabhaChakraborty** [comment]
cc: @matrixji

**Pull request merged**
